services:
  - type: web
    name: stock-manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn spectra_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: spectra_project.settings
      - key: PYTHON_VERSION
        value: 3.10
