# Generated by Django 5.0.6 on 2024-05-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=255)),
                ('regno', models.IntegerField()),
                ('gstno', models.CharField(max_length=255)),
                ('phoneno', models.IntegerField()),
                ('gmail', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalname', models.CharField(max_length=255)),
                ('gstno', models.CharField(max_length=255)),
                ('phoneno', models.IntegerField()),
                ('gmail', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra_project.category')),
            ],
        ),
        migrations.CreateModel(
            name='Medicalwisesales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('medicalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra_project.medical')),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra_project.product')),
            ],
        ),
        migrations.CreateModel(
            name='Doctorwisesales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('doctorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra_project.doctor')),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra_project.product')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra_project.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectra_project.subcategory'),
        ),
    ]
